version: "3.4"
services:
 vite_docker:
   image: node:alpine
   container_name: society_app_front_end
   entrypoint: /bin/sh
   ports:
     - 8000:8000
   working_dir: /srv/app
   volumes:
     - type: bind
       source: ./
       target: /srv/app
   tty: true