version: "3"
services:
  database:
    container_name: society_app_database
    image: mongo
    restart: always
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=societyAdminUser"
      - "MONGO_INITDB_ROOT_PASSWORD=12345678"
    networks:
      - node-network
  backend:
    build: .
    container_name: society_app_backend
    command: sh -c "node server.js"
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - node-network
      
volumes:
  mongodb-data:

networks:
  node-network:
    driver: bridge

